config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :preps
  resources :recipes
  resources :saved_recipes
  resources :saved_preps
  get "/discover", to: "recipes#public_index"
  get "/discover_preps", to: "preps#public_index"
  delete "/saved_preps", to: "saved_preps#delete"
  delete "/saved_recipes", to: "saved_recipes#delete"
  root to: "preps#index"
end

app/models/prep.rb
class Prep < ApplicationRecord
    belongs_to :user
    has_many :recipe_lists
    has_many :recipes, through: :recipe_lists
    has_many :ingredients_lists, through: :recipes

    validates :name, presence: true
    validates :user_id, presence: true

    
end

app/controllers/preps_controller.rb
class PrepsController < ApplicationController
    before_action :owned_by_current_user?, only: [:update]



    def new
        @prep = current_user.preps.build()
    end
    def show
        @prep = Prep.find(params[:id])
        @recipes = @prep.recipes
        @ingredients = @prep.ingredients_lists
        if current_user 
            @user_recipes_options = current_user.recipes.map{|r| [r.name, r.id]}
            @liked_recipes_options = current_user.liked_recipes.map{|r| [r.name, r.id]}
            @created_or_liked_recipes_options = [["Your recipes"] + [@user_recipes_options]] + [["Saved recipes"] + [@liked_recipes_options]]
            p @created_or_liked_recipes_options
            @owned = (@prep.user_id == current_user.id)
            @saved = SavedPrep.where(user_id: current_user.id, prep_id: @prep.id).any?
        end
        
    end
    def create
        @prep = current_user.preps.build(prep_params)
        if @prep.save
            flash[:success] = "Prep creation successful"
            redirect_to @prep
        else
            flas[:failure] = "Something went wrong"
            render :new, status: :unprocessable_entity
        end
    end
    def index
        if current_user
            @preps = current_user.preps
            @liked_preps = current_user.liked_preps
        else
            @preps = Prep.where(public: true)
        end
    end
    def update
        
        @prep = Prep.find(params[:id])
        if @prep.user_id != current_user.id
            redirect_to @prep
        else
            if params[:toggle_public] == "1"
                p "toggling public"
                if @prep.public == 0
                    @prep.public = 1
                else
                    @prep.public = 0
                end
                @prep.save
            end
            if params[:commit] == "remove this recipe"
                recipe = Recipe.find_by(name: params[:recipe_name])
                recipe_list = RecipeList.where(prep_id: @prep.id, recipe_id: recipe.id)
                RecipeList.delete(recipe_list.first)
                flash[:success] = "Recipe removed successfully"
                redirect_to @prep
            else
                
                @rl = @prep.recipe_lists.build(recipe_id: params[:recipe_id])
                @rl.save
                redirect_to @prep
            end
        end
    end
    def public_index
        @preps = Prep.where(public: true)
    end
    private
    def prep_params
        params.require(:prep).permit(:name)
    end

    def owned_by_current_user?
        if current_user
            Prep.find(params[:id]).user_id == current_user.id
        end
        return false
    end
end

app/helpers/preps_helper.rb
module PrepsHelper
end

app/views/preps/index.html.erb
<% if current_user %>

<h1>hello, <%=current_user.email%></h1>
<h4>These are your preps:</h4>
<ul>
<%@preps.each do |p|%>
<li><%= link_to p.name, p %></li>
<% end%>
</ul>
<%= link_to "create new prep", new_prep_path %>
<h4>These are your saved preps:</h4>
<ul>
<%@liked_preps.each do |p|%>
<li><%= link_to p.name, p %></li>
<% end%>
</ul>
<%= link_to "Discover more preps", "/discover_preps"%>

<% else %>

<h1>Public Preps:</h1>

<%@preps.each do |p|%>
<li><%= link_to p.name, p %></li>
<% end%>
<h4> <%=link_to "sign in", "/users/sign_in"%> to get started saving or creating your own preps</h4>
<% end %>

app/views/preps/new.html.erb
<h1>Create a prep!</h1>
<%= form_with model: @prep do |f| %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/preps/public_index.html.erb
<h1>Public Preps:</h1>
<ul>
<% @preps.each do |p| %>
<li><%= link_to p.name + " by " + p.user.email, p%></li>

<% end %>
</ul>

app/views/preps/show.html.erb
<h2><%=@prep.name%></h1>
<% if current_user %>
    <% if !@saved %>
        <%= form_with url: "/saved_preps" do |f| %>
            <%= f.hidden_field "prep", name: "saved_prep_id", value: @prep.id%>
            <%= f.submit "Save Prep" %>
        <% end %>
    <% else %>
        <%= form_with url: "/saved_preps", method: "DELETE" do |f| %>
            <%= f.hidden_field "prep", name: "saved_prep_id", value: @prep.id%>
            <%= f.submit "Unsave Prep" %>
        <% end %>
    <% end %>
<% end %>


<% if @owned %>
    <%= form_with method: "patch" do |f| %>
        <%= f.hidden_field "toggle_public_button", name: "toggle_public", value: 1%>
        <% if @prep.public == 0 %>
            <%= f.submit "Make Public"%>
            <% else %>
            <%= f.submit "Make Private"%>
        <% end %>
    <% end %>
<% else %>
    <h4>By <%=@prep.user.email%></h4>
<% end %>
<h4>recipes in this prep:</h4>
<% @recipes.each do |r| %>
    <h4> <%=link_to r.name, r%>
    <% if @owned %>
        <%= form_with method: "patch" do |f| %>
            
            <%= f.hidden_field "", name: "recipe_name", value: r.name%>
            <%= f.submit "remove this recipe"%>
        <% end%>
    <% end %> </h4>
<% end %>
<% if @owned %>
    add a recipe
    <%= form_with method: "patch" do |f| %>
    <%= f.select(:recipe_id, grouped_options_for_select(@created_or_liked_recipes_options))%>
    <%= f.submit %>
    <% end %>
<% end %>
<h4>Ingredients needed for this prep:</h4>
<ul>
<% @ingredients.each do |i| %>
<li> <%= Ingredient.find(i.ingredient_id).name %> 
    <%= ", " + i.amount.to_s if i.amount %> 
    <%= i.unit if i.unit %> </li>
<% end %>
</ul>