config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :preps
  resources :recipes
  resources :saved_recipes
  resources :saved_preps
  get "/discover", to: "recipes#public_index"
  get "/discover_preps", to: "preps#public_index"
  delete "/saved_preps", to: "saved_preps#delete"
  delete "/saved_recipes", to: "saved_recipes#delete"
  root to: "preps#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user

    has_many :ingredients_lists
    has_many :ingredients, through: :ingredients_lists
    has_many :saved_recipes
    
    validates :name, presence: true
    validates :user_id, presence: true

    accepts_nested_attributes_for :ingredients_lists, :allow_destroy => true
    accepts_nested_attributes_for :ingredients

    
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :owned_by_current_user?, only: [:update]
    def new
        @recipe = current_user.recipes.build()
    end
    def create
        @recipe = current_user.recipes.build(recipe_params)
        if @recipe.save
            flash[:success] = "Recipe creation successful"
            redirect_to @recipe
        else
            flash[:failure] = "Something went wrong"
            render :new, status: :unprocessable_entity
        end
    end
    def show
        @recipe = Recipe.find(params[:id])
        @ingredients_list = @recipe.ingredients_lists
        if current_user
            @owned = (@recipe.user_id == current_user.id)
            @saved = SavedRecipe.where(recipe_id: @recipe.id, user_id: current_user.id).any?
        end
    end
    def index
        if current_user
            @user_recipes = current_user.recipes
            @liked_recipes = current_user.liked_recipes
        else
            @user_recipes = Recipe.where(public: true)
        end
    end
    def public_index
        @recipes = Recipe.where(public: true).order_by()
    end
    def edit
        @recipe = Recipe.find(params[:id])
        
        @ingredients_lists = @recipe.ingredients_lists
    end
    def update
        @recipe = Recipe.find(params[:id])       
        @recipe.update(recipe_params)
        if params[:commit] == "Add ingredient"
            ni_params = new_ingredient_params
            ni_params[:ingredients_list][:ingredient_id] = Ingredient.find_or_create_by(name: ni_params[:ingredients_list][:name]).id
            ni_params[:ingredients_list][:recipe_id] = @recipe.id
            ni_params[:ingredients_list].delete(:name)

            @il = IngredientsList.new(ni_params[:ingredients_list])
            flash[:success] = "Ingredient added" if @il.save
            redirect_to edit_recipe_path(@recipe)
        else
            redirect_to @recipe
        end

    end
    private
    def recipe_params
        params.require(:recipe).permit(:public, :name, :user_id, :body , ingredients_lists_attributes: [:id, :ingredient_id, :recipe_id, :amount, :unit, :_destroy])
    end
    def new_ingredient_params
        params.require(:recipe).permit(ingredients_list: [:name, :unit, :amount])
    end
    def owned_by_current_user?
        if current_user
            Recipe.find(params[:id]).user_id == current_user.id
        end
        return false
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/edit.html.erb
<%= form_with model: @recipe do |f| %>
    <h4>Name:</h4>
    <%= f.text_field :name  %>
    <p>Make this public? <%= f.check_box :public %></p>
    <h4>Ingredients:</h4>
    <ul>
    <%= f.fields_for :ingredients_lists, @ingredients_lists do |f2|%>

        <li><%= @ingredients_lists[f2.index].ingredient.name %>     <%= f2.number_field :amount %> <%= f2.text_field :unit %> Delete: <%= f2.check_box :_destroy %></li>
    <%end%>
    </ul>

    <%= f.fields_for :ingredients_list  do |f3| %>
        New Ingredient name:
        <%= f3.text_field :name %>
        Amount:
        <%= f3.number_field :amount %>
        Unit:
        <%= f3.text_field :unit %>
        <%=f3.submit "Add ingredient"%>
    <% end %>
    <h4>Steps:</h4>
    <p><%= f.text_field :body %></p>
    <%= f.submit %>
<% end %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<% if current_user %>


<h4>Your recipes:</h4>
<ul>
<% @user_recipes.each do |r|%>
<li><%= link_to r.name, r %></li>
<% end %>
</ul>
<%= link_to "create new recipe", new_recipe_path %>

<ul>
<h4>Liked Recipes:</h4>
<%@liked_recipes.each do |r|%>
<li><%= link_to r.name, r %></li>
<% end %>
</ul>
<%= link_to "Discover new recipes", "/discover"%>

<% else %>
    <h4>Public Recipes</h4>
    <ul>
    <% @user_recipes.each do |r|%>
        <li><%= link_to r.name, r %></li>
    <% end %>
    </ul>
    <h4><%= link_to "Sign In", "/users/sign_in"%> To get started creating and saving recipes.</h4>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= form_with model: @recipe do |f| %>
<h4>Name:</h4>
<%= f.text_field :name %>
<h4>Steps:</h4>
<%= f.text_field :body %>
<br>
<%= f.submit %>
<% end %>

app/views/recipes/public_index.html.erb
<ul>
<h1>Public Recipes:</h1>
<% @recipes.each do |r| %>
<li><%= link_to r.name, r %></li>
<% end%>
</ul>

app/views/recipes/show.html.erb
<% if current_user%>
    <% if !@saved%>
        <%= form_with url: "/saved_recipes" do |f| %>
            <%= f.hidden_field "recipe", name: "saved_recipe_id", value: @recipe.id%>
            <%= f.submit "Save Recipe" %>
        <% end %>
    <%else%>
        <%= form_with url: "/saved_recipes", method: "delete" do |f| %>
            <%= f.hidden_field "recipe", name: "saved_recipe_id", value: @recipe.id%>
            <%= f.submit "Unsave Recipe" %>
        <% end %>
    <% end %>
<% end %>
<h1><%=@recipe.name%></h1>
<% if @recipe.public == 1 %><p> public recipe </p> <% end %>
<h4>
<% if @owned %>
    <%=link_to "edit", edit_recipe_path(@recipe)%>
<% else %>
    By <%=@recipe.user.email%>
<% end %></h4>
<h4>Ingredients:</h4>
<ul>
<%@ingredients_list.each do |i|%>
    <li><%=i.ingredient.name%>, <%= i.amount%> <%= i.unit%> </li>
<%end%>
</ul>
<h4>Steps:</h4>
<p><%=@recipe.body%></p>